name: Vue App CI/CD
on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci
    ## veracode
      - name: Zip
        run: zip -r veracode.zip src -x node_modules/**\* 
      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: veracode.zip

  Veracode_SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA }}
        run: |
          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --pull-request --allow-dirty

  # Schedule por causa da concorrencia, esse STEP gera relatórios
  # Cenário de subir a versão
  # Veracode_SAST_REPORTS:
  #   name: SAST Reports
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download Artefato
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: pacoteVeracode
  #     - uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
  #       env:
  #         VID: ${{ secrets.VID }} # Lembrar de criar as credenciais no Secrets
  #         VKEY: ${{ secrets.VKEY }}
  #         AppName: Github Actions - ${{ github.repository }}
  #       with:
  #         vid: '$VID'
  #         vkey: '$VKEY'
  #         criticality: 'VeryHigh'
  #         appname: '$AppName'
  #         createsandbox: true
  #         sandboxname: dev
  #         filepath: 'veracode.zip'
  #         deleteIncompleteScan: false
  #         version: ${{ github.run_id }}

  Veracode_PipelineScan:
    name: SAST
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - name: Veracode Pipeline Scan
        env:
          VID: ${{ secrets.VID }} 
          VKEY: ${{ secrets.VKEY }}
          CaminhoArquivo: './veracode.zip'
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid $VID -vkey $VKEY -f $CaminhoArquivo --issue_details true
          
